### ISSUE TITLE
mmEffectCancel error return type for maxmod9.h

### ISSUE THREAD

**Issue by Lorenzooone** [blocksds/maxmod#13]
https://github.com/blocksds/maxmod/blob/d72ce2b934365ec00377498ea69ec62bd70f8f54/source_ds9/mm_comms9.c#L376
mmEffectCancel's return type in maxmod9.h should be void.

mmEffectCancel does return mm_word in ARM7 and GBA code, which is why it's checked by mmEffectEx in the "source" folder.
However code in "source" is not compiled when it comes to ARM9.

In fact, you can also find mmEffectEx's ARM9 code in the same file linked above.

**Comment by AntonioND** [comment]
While that is true, it looks like some code is checking the returned value by that function:

https://github.com/blocksds/maxmod/blob/3e26430dd90310259e5469838e6b9852dc518667/source/mm_effect.s#L175

So either the return type is mm_word/bool or there is a bug in this code.

**Comment by Lorenzooone** [comment]
> https://github.com/blocksds/maxmod/blob/d72ce2b934365ec00377498ea69ec62bd70f8f54/source_ds9/mm_comms9.c#L376
> 
> mmEffectCancel's return type in maxmod9.h should be void.
> 
> mmEffectCancel does return mm_word in ARM7 and GBA code, which is why it's checked by mmEffectEx in the "source" folder. However code in "source" is not compiled when it comes to ARM9.
> 
> In fact, you can also find mmEffectEx's ARM9 code in the same file linked above.

source/mm_effect.s is not ARM9 code.

**Comment by AntonioND** [comment]
This should take care of it: https://github.com/blocksds/maxmod/commit/558fd4f945eed3494706e0f46b2bee1847217639
